version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"                 
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "pycord"
        versions: ["<26.1.0"]
    labels:
      - "dependencies"
    groups:
      python-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    open-pull-requests-limit: 3
    labels:
      - "ci"
      - "github-actions"
    groups:
      github-ci:
        patterns:
          - "*"
