- name: bug
  color: d73a4a
  description: Something isn't working

- name: feature
  color: a2eeef
  description: New feature or request

- name: enhancement
  color: 84b6eb
  description: Code improvement or refactor

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: question
  color: d876e3
  description: Further information is requested

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: Extra attention is needed

- name: security
  color: ee0701
  description: Security vulnerability or related

- name: ci
  color: cfd3d7
  description: Continuous Integration related

- name: github-actions
  color: f9d0c4
  description: GitHub Actions related

- name: dependencies
  color: 0366d6
  description: Dependency updates

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right
