name: "🐞 Bug Report"
description: Report a bug or unexpected behavior.
title: "[Bug] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Please describe the bug clearly so we can fix it fast.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: What happened? What did you expect instead?
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Start the bot
        2. Run `!play ...`
        3. Crash
      required: true

  - type: input
    id: version
    attributes:
      label: Wavecord Version
      placeholder: e.g. 0.1.0
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error / Logs
      description: Include relevant errors, tracebacks, or logs.
