name: "✨ Feature Request"
description: Suggest a new feature or improvement.
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make Wavecord better!

  - type: textarea
    id: proposal
    attributes:
      label: Feature Idea
      placeholder: Clearly describe the feature or improvement.
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      placeholder: Why would this feature be useful? When would you use it?
